# Generated by Django 5.2.4 on 2025-07-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('marks', models.FloatField()),
                ('subjects', models.CharField(help_text='Comma-separated subjects', max_length=255)),
            ],
        ),
    ]
